include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - public_member_api_docs
    - always_declare_return_types
    - camel_case_types
    - empty_constructor_bodies
    - annotate_overrides
    - slash_for_doc_comments
    - lines_longer_than_80_chars
